# Metadata Block
metadatablock.DCATMetadata.displayName=DCAT AP NL3.0 Metadata

# Field labels and descriptions
datasetfieldtype.DCATpublisher.title=Publisher
datasetfieldtype.DCATpublisher.description=The organisation responsible for publishing the dataset.

datasetfieldtype.DCATaccessRights.title=Access Rights
datasetfieldtype.DCATaccessRights.description=This property contains information indicating whether the dataset is publicly accessible, has access restrictions, or is not accessible.

datasetfieldtype.DCATeuTheme.title=EU Theme
datasetfieldtype.DCATeuTheme.description=The EU theme of the dataset.

datasetfieldtype.DCATapplicableLegislation.title=Applicable Legislation
datasetfieldtype.DCATapplicableLegislation.description=This property contains the legislation that mandates the creation or management of the dataset.

datasetfieldtype.DCAThvdCategory.title=HVD Category
datasetfieldtype.DCAThvdCategory.description=This property contains the HVD category to which this dataset belongs, if the dataset falls under the High-Value Datasets Implementing Regulation.

# Controlled vocabulary for DCATMetadata (sanitized keys)

# Publisher
controlledvocabulary.DCATpublisher.geo-survey-nl=TNO Geological Survey of the Netherlands

# Access Rights
controlledvocabulary.DCATaccessRights.public=Public

# Theme (EU vocab URIs)
controlledvocabulary.DCATeuTheme.ener=Energy
controlledvocabulary.DCATeuTheme.envi=Environment
controlledvocabulary.DCATeuTheme.tech=Science and technology

# Applicable Legislation
controlledvocabulary.DCATapplicableLegislation.hvd=Implementing Regulation High-Value Datasets
controlledvocabulary.DCATapplicableLegislation.mijnbouwwet=Mining Act of the Netherlands

# HVD Category
controlledvocabulary.DCAThvdCategory.area-management=Area management / restriction / regulation zones & reporting units
controlledvocabulary.DCAThvdCategory.energy-resources=Energy resources
controlledvocabulary.DCAThvdCategory.environmental-monitoring-facilities=Environmental monitoring facilities
controlledvocabulary.DCAThvdCategory.geology=Geology
controlledvocabulary.DCAThvdCategory.mineral-resources=Mineral resources
controlledvocabulary.DCAThvdCategory.industrial-facilities=Production and industrial facilities
controlledvocabulary.DCAThvdCategory.soil=Soil
