# Metadata Block
metadatablock.GDNMetadata.displayName=Geological Survey of the Netherlands Metadata

# Field labels and descriptions
datasetfieldtype.GDNtheme.title=GDN Theme
datasetfieldtype.GDNtheme.description=A theme within the interdisciplinary sciences focused on the solid Earth, its physical and chemical components (rocks, minerals, processes)?and its subsurface systems.

# Controlled vocabulary for GDNMetadata (sanitized keys)

# GDNtheme
controlledvocabulary.GDNtheme.future-proof-land-use=Future-proof land use
controlledvocabulary.GDNtheme.groundwater-stewardship=Groundwater stewardship
controlledvocabulary.GDNtheme.geo-energy=Geo energy
controlledvocabulary.GDNtheme.raw-materials=Raw materials
